#!/bin/bash
WINEPATH=C:\\BC5\\BIN SDL_VIDEODRIVER=dummy wine bcc -ml -4 -O2 -ISRC/ -ISRC/GRAPHICS/ -ISRC/INPUT SRC/NOCTIS.CPP SRC/NOCTIS-0.CPP SRC/NOCTIS-1.CPP SRC/GAME.CPP SRC/GRAPHICS/SCREEN.CPP SRC/INPUT/MOUSE.CPP
rm *.obj
